server:
  port: 30000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tGToHFUkFWYYMuzZfzq
      secret-key: tYJoi7EdAUO04XC9oz7KNGsi9RH3WS
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-zqn
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        appcode: d0f6de913f63402a87d901c3f1a975b2
        id: TPL_0000
  application:
    name: gulimall-third-party